name: Build and Test Storage API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: launch mongodb
        run: docker run -d -p 27017:27017 -e MONGO_INITDB_DATABASE=storage_app --name mongo mongo
        
      - name: Run tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t storage_app:latest .

      - name: Check Docker image size
        run: |
          docker images storage_app --format "table {{.Repository}}\t{{.Size}}"

      #- name: Verify image memory/disk constraints
      #  run: |
      #   docker run --memory=1g --rm storage_app java -version
